CREATE TABLE IF NOT EXISTS "Clientes_Shelby" (
	"id_cliente" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome_cliente" VARCHAR(255) NOT NULL,
	"setor" VARCHAR(100) NOT NULL,
	"cidade_origem" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id_cliente")
);

CREATE TABLE IF NOT EXISTS "Operações_Portuarias" (
	"id_operacoes" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cliente_id" INTEGER NOT NULL,
	"descrição_carga" VARCHAR(150) NOT NULL,
	"valor_operacao" NUMERIC NOT NULL,
	"status_envio" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_operacoes")
);

ALTER TABLE "Operações_Portuarias"
ADD FOREIGN KEY("cliente_id") REFERENCES "Clientes_Shelby"("id_cliente")
ON UPDATE NO ACTION ON DELETE NO ACTION;