CREATE TABLE IF NOT EXISTS "Empresas_Grupo" (
	"id_empresa" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome_empresa" VARCHAR(100) NOT NULL,
	"tipo_unidade" VARCHAR(50) NOT NULL,
	"pais_sede" VARCHAR(50) NOT NULL,
	PRIMARY KEY("id_empresa")
);

CREATE TABLE IF NOT EXISTS "Contratos_Parcerias" (
	"id_contrato" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cliente_id" INTEGER NOT NULL,
	"empresa_id" INTEGER NOT NULL,
	"data_inicio" DATE NOT NULL,
	"valor_total" NUMERIC NOT NULL,
	"status_contrato" VARCHAR(50) NOT NULL,
	PRIMARY KEY("id_contrato")
);

CREATE TABLE IF NOT EXISTS "Clientes_Globais" (
	"id_cliente" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome_cliente" VARCHAR(100) NOT NULL,
	"setor_atuação" VARCHAR(100) NOT NULL,
	"pais_origem" VARCHAR(50) NOT NULL,
	"contato_responsavel" VARCHAR(100) NOT NULL,
	"nivel_classificação" VARCHAR(30) NOT NULL,
	PRIMARY KEY("id_cliente")
);

CREATE TABLE IF NOT EXISTS "Futuras_Transacoes" (
	"id_fatura" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"contrato_id" INTEGER NOT NULL,
	"data_emissao" DATE NOT NULL,
	"valor_faturado" NUMERIC NOT NULL,
	"estado_pagamento" VARCHAR(30) NOT NULL,
	PRIMARY KEY("id_fatura")
);

CREATE TABLE IF NOT EXISTS "Projetos_Setoriais" (
	"id_projeto" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"contrato_id" INTEGER NOT NULL,
	"nome_projeto" VARCHAR(150) NOT NULL,
	"categoria_tecnologia" VARCHAR(100) NOT NULL,
	"orcamento_alocado" NUMERIC NOT NULL,
	PRIMARY KEY("id_projeto")
);

ALTER TABLE "Contratos_Parcerias"
ADD FOREIGN KEY("cliente_id") REFERENCES "Clientes_Globais"("id_cliente")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Contratos_Parcerias"
ADD FOREIGN KEY("empresa_id") REFERENCES "Empresas_Grupo"("id_empresa")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Projetos_Setoriais"
ADD FOREIGN KEY("contrato_id") REFERENCES "Contratos_Parcerias"("id_contrato")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Futuras_Transacoes"
ADD FOREIGN KEY("contrato_id") REFERENCES "Contratos_Parcerias"("id_contrato")
ON UPDATE NO ACTION ON DELETE NO ACTION;